apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-config-maps
  labels:
    {{- include "c9s.meta-labels" . | nindent 4 }}
data:
  {{- range $path, $_ :=  .Files.Glob  "config/**.*" }}
  {{ $path | trimPrefix "config/" }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{ end }}
