---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
  labels:
    {{- include "c9s.meta-labels" . | nindent 4 }}
data:
  # Format is <ingress-port>: <namespace>/<service>:<service-port>
  1883: "c9s/rabbitmq:mqtt-tcp"
