---
apiVersion: v1
kind: Service
metadata:
  name: pca9685-service
  labels:
    {{- include "c9s.service-labels" .Values.pca9685_service | nindent 4 }}
    {{- include "c9s.meta-labels" . | nindent 4 }}
spec:
  selector:
    role: pca9685-service
  ports:
    - port: 9999
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pca9685-service-ingress
  labels:
    {{- include "c9s.service-labels" .Values.pca9685_service | nindent 4 }}
    {{- include "c9s.meta-labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: pca9685
    http:
  - http:
      paths:
        - path: /pca9685(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: pca9685-service
              port:
                name: http
---
{{ if .Values.pca9685_workload.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pca9685-service-deployment
  labels:
    {{- include "c9s.workload-labels" .Values.pca9685_workload | nindent 4 }}
    {{- include "c9s.meta-labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      role: pca9685-service
  replicas: {{ .Values.pca9685_service.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        role: pca9685-service
        {{- include "c9s.workload-labels" .Values.pca9685_workload | nindent 8 }}
        {{- include "c9s.meta-labels" . | nindent 8 }}
    spec:
      containers:
        - name: pca9685-service
          image: {{ template "application.image" (dict "Values" .Values "Image" .Values.pca9685_workload.image) }}
          args:
            - --config-file-path
            - /etc/pca9685-service/pca9685.yaml
          env:
            - name: ROCKET_CONFIG
              value: /etc/pca9685-service/rocket.toml
            - name: RUST_LOG
              value: debug
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          volumeMounts:
            - name: rpi-i2c-device
              mountPath: /dev/i2c-1
            - name: auto-config-maps
              mountPath: /etc/pca9685-service/pca9685.yaml
              subPath: pca9685.yaml
            - name: auto-config-maps
              mountPath: /etc/pca9685-service/rocket.toml
              subPath: rocket.toml
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
      securityContext:
        privileged: true
      volumes:
        - name: auto-config-maps
          configMap:
            name: auto-config-maps
        - name: rpi-i2c-device
          hostPath:
            path: /dev/i2c-1
            type: CharDevice
{{ end }}
