- name: Upgrade the OS (apt-get upgrade)
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoclean: true
    autoremove: true
  notify:
    - Restart rpi

- name: Install OS packages/prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - raspberrypi-bootloader
      - raspberrypi-kernel
      - snapd
    state: present
  notify:
    - Restart rpi

- name: Flush handlers after upgrade
  ansible.builtin.meta: flush_handlers

- name: Docker host prerequisites
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install Docker components
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add pi user to applicable groups
  ansible.builtin.user:
    name: "{{ rpi_user }}"
    groups:
      - docker
    append: true

- name: Enable container features (/boot/cmdline.txt)
  ansible.builtin.replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  notify:
    - Restart rpi

- name: Enable I2C (/boot/config.txt)
  ansible.builtin.lineinfile:
    dest: /boot/config.txt
    regexp: '^#dtparam=i2c_arm=on$'
    line: 'dtparam=i2c_arm=on'
  notify:
    - Restart rpi

- name: Flush handlers Docker / container / I2C setup
  ansible.builtin.meta: flush_handlers
