- name: Configure ArgoCD for the c9s application
  hosts: rpi_hosts
  become: true
  roles:
    - argocd
  handlers:
    - import_tasks: roles/common/handlers/restart-rpi.yaml
      tags:
        - skip_ansible_lint
  vars_files:
      - config/vars.yaml
