---
- hosts: rpi
  become: true
  tasks:
    - name: Upgrade the OS (apt-get upgrade)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
      notify:
        - Restart rpi

    - name: Install packages/prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - raspberrypi-bootloader
          - raspberrypi-kernel
          - snapd
        state: latest
      notify:
        - Restart rpi

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Docker host prerequisites
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Install Docker components
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true
            
    - name: Install microk8s
      community.general.snap:
        name:
          - microk8s
        classic: true

    - name: Add pi user to applicable groups
      ansible.builtin.user:
        name: pi
        groups:
          - docker
          - microk8s
        append: true

    - name: Enable microk8s plugins
      ansible.builtin.include_role:
        name: gepaplexx.microk8s
      vars:
          microk8s_plugins:
            istio: true
            ingress: true

    - name: Enable container features (/boot/cmdline.txt)
      replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "cgroup_enable=cpuset"
        - "cgroup_memory=1"
        - "cgroup_enable=memory"

    - name: Enable I2C (/boot/config.txt)
      lineinfile:
        dest: /boot/config.txt
        regexp: '^#dtparam=i2c_arm=on$'
        line: 'dtparam=i2c_arm=on'

  handlers:
    - name: Restart rpi
      ansible.builtin.reboot:
