- name: Configure Raspberry Pi for carbernetes
  hosts: rpi_hosts
  become: true
  roles:
    - os
    - k8s
  handlers:
    - import_tasks: roles/common/handlers/restart-rpi.yaml
      tags:
        - skip_ansible_lint
  vars_files:
      - config/vars.yaml