- name: Create /etc/argocd/
  file:
    path: /etc/argocd
    state: directory

- name: Expand ArgoCD Git repo secret template (rpi)
  ansible.builtin.template:
    src: argocd-repo-secret.yaml.j2
    dest: /etc/argocd/argocd-repo-secret.yaml
  vars:
    repo_secret_name: "{{ argocd_repo_secret_name }}"
    repo_project: "{{ argocd_project }}"
    repo_url: "{{ argocd_repo_url }}"
    repo_private_key: "{{ argocd_repo_private_key }}"

- name: Expand ArgoCD c9s Application template (rpi)
  ansible.builtin.template:
    src: argocd-c9s-application.yaml.j2
    dest: /etc/argocd/argocd-c9s-application.yaml

- name: Expand ArgoCD RabbitMQ Application template (rpi)
  ansible.builtin.template:
    src: argocd-rabbitmq-application.yaml.j2
    dest: /etc/argocd/argocd-rabbitmq-application.yaml

- name: Configure repo secrets for ArgoCD
  kubernetes.core.k8s:
    apply: true
    state: present
    src: /etc/argocd/argocd-repo-secret.yaml
    kubeconfig: /etc/kubeconfig

- name: Configure ArgoCD RabbitMQ application
  kubernetes.core.k8s:
    apply: true
    state: present
    src: /etc/argocd/argocd-rabbitmq-application.yaml
    kubeconfig: /etc/kubeconfig

- name: Configure ArgoCD 9s application
  kubernetes.core.k8s:
    apply: true
    state: present
    src: /etc/argocd/argocd-c9s-application.yaml
    kubeconfig: /etc/kubeconfig
