image_repository: ghcr.io/kerrys-learning-lab

host: raspberrypi.local

pca9685_service:
  component: servo-control

pca9685_workload:
  enabled: true
  component: servo-control
  image:
    name: pca9685-service
    tag: v1.3.0-arm64

accelerometer_workload:
  enabled: true
  component: sensors
  image:
    name: accelerometer-service
    tag: v1.1.0-arm64
