image_repository: ghcr.io/kerrys-learning-lab

pca9685_service:
  component: servo-control

pca9685_workload:
  # Should only ever be 1 (enabled) or 0 (disabled)
  replicas: 0
  component: servo-control
  image:
    name: pca9685-service
    tag: v1.1.0-arm64
