- name: Install microk8s
  community.general.snap:
    name:
      - microk8s
    classic: true

- name: Add pi user to applicable groups
  ansible.builtin.user:
    name: pi
    groups:
      - microk8s
    append: true

- name: Install python packages for k8s management
  ansible.builtin.pip:
    name:
      - kubernetes

- name: Status of mycommunity repo
  ansible.builtin.command: /snap/bin/microk8s addons repo list
  register: microk8s_community_repo
  changed_when: false

- name: Add custom microk8s community repo
  ansible.builtin.command: >
    {{ microk8s }} addons repo add mycommunity {{ microk8s_community_addon_repo }}
  when: microk8s_community_repo.stdout.find('mycommunity') == -1

- name: Status of microk8s dns add-on
  ansible.builtin.command: "{{ microk8s }} status -a dns"
  register: microk8s_dns_addon
  changed_when: false

- name: Install microk8s dns add-on
  ansible.builtin.command: "{{ microk8s }} enable dns"
  when: microk8s_dns_addon.stdout.find('enabled') == -1

- name: Status of microk8s argocd add-on
  ansible.builtin.command: "{{ microk8s }} status -a argocd"
  register: microk8s_argocd_addon
  changed_when: false

- name: Install microk8s argocd add-on
  ansible.builtin.command: "{{ microk8s }} enable argocd"
  when: microk8s_argocd_addon.stdout.find('enabled') == -1

- name: Get microk8s kubectl configuration
  ansible.builtin.command: "{{ microk8s }} config"
  register: microk8s_kubectl_config
  changed_when: false

- name: Save kubeconfig (rpi)
  ansible.builtin.copy:
    content: "{{ microk8s_kubectl_config.stdout }}"
    dest: /etc/kubeconfig
    mode: '644'

- name: Save kubeconfig (local)
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ microk8s_kubectl_config.stdout }}"
    dest: "{{ local_kubeconfig_dest_path }}/kubectl-config-{{ inventory_hostname }}.yaml"
    owner: "{{ local_owner }}"
    group: "{{ local_group }}"
    mode: '644'

- name: Create /etc/argocd/
  file:
    path: /etc/argocd
    state: directory

- name: Expand ArgoCD Git repo secret template (rpi)
  ansible.builtin.template:
    src: argocd-repo-secret.yaml.j2
    dest: /etc/argocd/argocd-repo-secret.yaml
  vars:
    repo_secret_name: "{{ argocd_repo_secret_name }}"
    repo_project: "{{ argocd_project }}"
    repo_url: "{{ argocd_repo_url }}"
    repo_private_key: "{{ argocd_repo_private_key }}"

- name: Expand ArgoCD Application template (rpi)
  ansible.builtin.template:
    src: argocd-application.yaml.j2
    dest: /etc/argocd/argocd-application.yaml

- name: Configure repo secrets for ArgoCD
  kubernetes.core.k8s:
    apply: true
    state: present
    src: /etc/argocd/argocd-repo-secret.yaml
    kubeconfig: /etc/kubeconfig

- name: Configure ArgoCD application
  kubernetes.core.k8s:
    apply: true
    state: present
    src: /etc/argocd/argocd-application.yaml
    kubeconfig: /etc/kubeconfig
