- name: Install microk8s
  community.general.snap:
    name:
      - microk8s
    classic: true

- name: Add pi user to applicable groups
  ansible.builtin.user:
    name: pi
    groups:
      - microk8s
    append: true

- name: Install python packages for k8s management
  ansible.builtin.pip:
    name:
      - kubernetes

- name: Configure custom microk8s repository
  microk8s:
    repo:
      name: mycommunity
      url: "{{ microk8s_community_addon_repo }}"

- name: Configure microk8s addons
  microk8s:
    addons:
      name:
        - argocd
        - dns
        - ingress
        - registry

- name: Get microk8s kubectl configuration
  ansible.builtin.command: "{{ microk8s }} config"
  register: microk8s_kubectl_config
  changed_when: false

- name: Save kubeconfig (rpi)
  ansible.builtin.copy:
    content: "{{ microk8s_kubectl_config.stdout }}"
    dest: /etc/kubeconfig
    mode: '644'

- name: Save kubeconfig (local)
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ microk8s_kubectl_config.stdout }}"
    dest: "{{ local_kubeconfig_dest_path }}/kubectl-config-{{ inventory_hostname }}.yaml"
    owner: "{{ local_owner }}"
    group: "{{ local_group }}"
    mode: '644'
